version: "3.3"
networks:
  traefik:
services:

  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=0.0.0.0:80"
      - "--api"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
  api1:
    image: api_1
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api1.rule=PathPrefix(`/rest/api1/`) && Host(`localhost`)"
      - "traefik.http.services.api1-service.loadbalancer.server.port=8081"
      - "traefik.http.routers.api1.entrypoints=web"
    networks:
      - traefik
  api2:
    image: api_2
    ports:
      - "8082:8082"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api2.rule=PathPrefix(`/rest/api2/`) && Host(`localhost`)"
      - "traefik.http.services.api1-service.loadbalancer.server.port=8082"
      - "traefik.http.routers.api2.entrypoints=web"
    networks:
      - traefik